yo

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -42,6 +42,11 @@ jobs:
         run: |-
           docker-compose -f docker-compose.prod.yml build app
           IMAGE_ID=$(docker-compose -f docker-compose.prod.yml images -q app)
+          echo "FastAPI Service Image ID: $IMAGE_ID"
+          if [ -z "$IMAGE_ID" ]; then
+            echo "Error: IMAGE_ID is empty. Exiting."
+            exit 1
+          fi
           docker tag $IMAGE_ID "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
           docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
 
