yo

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -40,13 +40,24 @@ jobs:
 
       - name: Build and Push Container
         run: |-
+          echo "Building Docker image..."
           docker-compose -f docker-compose.prod.yml build app
-          IMAGE_ID=$(docker-compose -f docker-compose.prod.yml images -q app)
+          BUILD_EXIT_CODE=$?
+          if [ $BUILD_EXIT_CODE -ne 0 ]; then
+            echo "Docker build failed. Exiting."
+            exit $BUILD_EXIT_CODE
+          fi
+          echo "Docker build succeeded."
+
+          echo "Retrieving image ID..."
+          IMAGE_ID=$(docker images --format '{{.ID}}' --filter "reference=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/app:${{ github.sha }}")
           echo "FastAPI Service Image ID: $IMAGE_ID"
           if [ -z "$IMAGE_ID" ]; then
             echo "Error: IMAGE_ID is empty. Exiting."
             exit 1
           fi
+
+          echo "Tagging Docker image..."
           docker tag $IMAGE_ID "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
           docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
 
